source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'ZeroShare' do
	pod 'HandyJSON', '~> 5.0.0'
	pod 'SnapKit', '~> 5.0.0'
	pod 'Alamofire', '~> 5.0.0-beta.5'
	pod 'SwiftyJSON', '~> 5.0.0'

  pod 'MXSegmentedPager', '~> 3.3.0'
  pod 'SocketRocket', '~> 0.5.1'
  
end
